// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stormy_SilverioAP1_P2.DAL;

#nullable disable

namespace Stormy_SilverioAP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stormy_SilverioAP1_P2.Models.AsignacionesPuntos", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPuntos")
                        .HasColumnType("int");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("EstudianteId");

                    b.ToTable("AsignacionesPuntos");
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P2.Models.DetalleAsignacion", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int?>("AsignacionesPuntosIdAsignacion")
                        .HasColumnType("int");

                    b.Property<int>("CantidadPuntos")
                        .HasColumnType("int");

                    b.Property<int>("IdAsignacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoPuntoId")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("AsignacionesPuntosIdAsignacion");

                    b.ToTable("DetalleAsignaciones");
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P2.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<int>("BalancePuntos")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteId = 1,
                            BalancePuntos = 0,
                            Edad = 20,
                            Email = "ana@universidad.edu",
                            Nombres = "Ana Martínez"
                        },
                        new
                        {
                            EstudianteId = 2,
                            BalancePuntos = 0,
                            Edad = 22,
                            Email = "carlos@universidad.edu",
                            Nombres = "Carlos Pérez"
                        },
                        new
                        {
                            EstudianteId = 3,
                            BalancePuntos = 0,
                            Edad = 21,
                            Email = "laura@universidad.edu",
                            Nombres = "Laura Rodríguez"
                        });
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P2.Models.TiposPuntos", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorPuntos")
                        .HasColumnType("int");

                    b.HasKey("TipoId");

                    b.ToTable("TiposPuntos");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Activo = true,
                            Color = "primary",
                            Descripcion = "Participación en clase",
                            Icono = "bi-hand-thumbs-up",
                            Nombre = "Participación",
                            ValorPuntos = 5
                        },
                        new
                        {
                            TipoId = 2,
                            Activo = true,
                            Color = "success",
                            Descripcion = "Entrega de tarea",
                            Icono = "bi-journal-check",
                            Nombre = "Tarea Entregada",
                            ValorPuntos = 10
                        },
                        new
                        {
                            TipoId = 3,
                            Activo = true,
                            Color = "warning",
                            Descripcion = "Entrega de proyecto",
                            Icono = "bi-lightbulb",
                            Nombre = "Proyecto",
                            ValorPuntos = 20
                        });
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P2.Models.AsignacionesPuntos", b =>
                {
                    b.HasOne("Stormy_SilverioAP1_P2.Models.Estudiantes", "Estudiantes")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P2.Models.DetalleAsignacion", b =>
                {
                    b.HasOne("Stormy_SilverioAP1_P2.Models.AsignacionesPuntos", null)
                        .WithMany("ListaDetalle")
                        .HasForeignKey("AsignacionesPuntosIdAsignacion");
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P2.Models.AsignacionesPuntos", b =>
                {
                    b.Navigation("ListaDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
